### ISSUE TITLE
Cleric Crash

### ISSUE THREAD

**Issue by Anigmatics** [ollieread/TechnoMagi#18] opened 2015-04-03 06:16 UTC
The game crashes when I try to choose the cleric class

---- Minecraft Crash Report ----
// Don't do that.

Time: 02/04/15 11:13 PM
Description: Unexpected error

java.lang.ArithmeticException: / by zero
	at com.ollieread.technomagi.client.gui.window.WindowOverlay.updateContent(WindowOverlay.java:63)
	at com.ollieread.technomagi.client.gui.window.WindowOverlay.<init>(WindowOverlay.java:33)
	at com.ollieread.technomagi.client.gui.GuiTechnomagi.init(GuiTechnomagi.java:37)
	at com.ollieread.technomagi.client.gui.GuiTechnomagi.onRenderExperienceBar(GuiTechnomagi.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_GuiTechnomagi_onRenderExperienceBar_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:544)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:150)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.ollieread.technomagi.client.gui.window.WindowOverlay.updateContent(WindowOverlay.java:63)
	at com.ollieread.technomagi.client.gui.window.WindowOverlay.<init>(WindowOverlay.java:33)
	at com.ollieread.technomagi.client.gui.GuiTechnomagi.init(GuiTechnomagi.java:37)
	at com.ollieread.technomagi.client.gui.GuiTechnomagi.onRenderExperienceBar(GuiTechnomagi.java:48)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_GuiTechnomagi_onRenderExperienceBar_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:544)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:150)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Enigmas'/245, l='MpServer', x=-295.90, y=70.62, z=151.64]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-248,64,152), Chunk: (at 8,4,8 in -16,9; contains blocks -256,0,144 to -241,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4342 game time, 4342 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 102 total; [EntityCreeper['Creeper'/31, l='MpServer', x=-375.56, y=13.00, z=95.03], EntityBat['Bat'/32, l='MpServer', x=-364.84, y=41.76, z=96.57], EntitySheep['Sheep'/33, l='MpServer', x=-378.81, y=79.00, z=220.53], EntitySheep['Sheep'/35, l='MpServer', x=-375.34, y=79.00, z=217.47], EntitySkeleton['Skeleton'/37, l='MpServer', x=-375.31, y=11.00, z=229.31], EntitySkeleton['Skeleton'/38, l='MpServer', x=-377.69, y=11.00, z=229.31], EntitySpider['Spider'/39, l='MpServer', x=-376.78, y=11.00, z=232.28], EntityBat['Bat'/41, l='MpServer', x=-350.94, y=33.83, z=93.51], EntityBat['Bat'/42, l='MpServer', x=-361.15, y=41.61, z=88.90], EntityBat['Bat'/43, l='MpServer', x=-361.08, y=41.06, z=93.17], EntityCreeper['Creeper'/44, l='MpServer', x=-360.53, y=22.03, z=103.20], EntityCreeper['Creeper'/45, l='MpServer', x=-360.50, y=19.00, z=97.59], EntityCreeper['Creeper'/46, l='MpServer', x=-361.50, y=20.00, z=97.50], EntityZombie['Zombie'/47, l='MpServer', x=-363.50, y=12.00, z=219.50], EntityCreeper['Creeper'/48, l='MpServer', x=-362.50, y=12.00, z=218.50], EntitySkeleton['Skeleton'/49, l='MpServer', x=-365.50, y=12.00, z=219.50], EntitySkeleton['Skeleton'/50, l='MpServer', x=-355.09, y=32.00, z=209.56], EntityCreeper['Creeper'/51, l='MpServer', x=-367.00, y=12.00, z=231.41], EntityBat['Bat'/60, l='MpServer', x=-345.50, y=29.00, z=98.25], EntitySheep['Sheep'/61, l='MpServer', x=-350.99, y=71.00, z=165.41], EntitySheep['Sheep'/62, l='MpServer', x=-350.28, y=71.00, z=160.59], EntitySheep['Sheep'/63, l='MpServer', x=-351.09, y=71.00, z=163.38], EntityCreeper['Creeper'/64, l='MpServer', x=-341.53, y=22.00, z=193.03], EntityZombie['Zombie'/65, l='MpServer', x=-340.07, y=22.35, z=190.32], EntityChicken['Chicken'/66, l='MpServer', x=-340.16, y=22.00, z=190.38], EntityCreeper['Creeper'/67, l='MpServer', x=-345.00, y=23.00, z=185.41], EntityCreeper['Creeper'/68, l='MpServer', x=-345.50, y=28.00, z=195.50], EntityBat['Bat'/69, l='MpServer', x=-332.25, y=24.00, z=207.75], EntityCreeper['Creeper'/70, l='MpServer', x=-344.50, y=41.00, z=197.50], EntityZombie['Zombie'/71, l='MpServer', x=-337.28, y=31.00, z=212.31], EntitySheep['Sheep'/76, l='MpServer', x=-320.34, y=79.00, z=117.50], EntitySheep['Sheep'/77, l='MpServer', x=-331.78, y=72.00, z=133.66], EntitySheep['Sheep'/78, l='MpServer', x=-324.25, y=71.00, z=154.28], EntitySheep['Sheep'/79, l='MpServer', x=-333.97, y=72.00, z=165.97], EntitySkeleton['Skeleton'/80, l='MpServer', x=-331.59, y=26.00, z=186.03], EntityBat['Bat'/81, l='MpServer', x=-338.38, y=23.18, z=194.07], EntityBat['Bat'/82, l='MpServer', x=-331.42, y=22.18, z=199.26], EntityBat['Bat'/83, l='MpServer', x=-332.99, y=24.68, z=205.91], EntityBat['Bat'/84, l='MpServer', x=-330.25, y=23.09, z=203.17], EntitySheep['Sheep'/89, l='MpServer', x=-319.53, y=73.00, z=130.53], EntityZombie['Zombie'/90, l='MpServer', x=-315.03, y=18.00, z=222.47], EntityZombie['Zombie'/91, l='MpServer', x=-304.50, y=14.00, z=227.50], EntitySkeleton['Skeleton'/99, l='MpServer', x=-295.25, y=55.00, z=154.31], EntitySquid['Squid'/100, l='MpServer', x=-299.22, y=56.25, z=182.50], EntitySkeleton['Skeleton'/101, l='MpServer', x=-301.14, y=45.00, z=205.24], EntitySquid['Squid'/102, l='MpServer', x=-295.53, y=58.19, z=196.50], EntitySquid['Squid'/103, l='MpServer', x=-299.50, y=55.88, z=194.56], EntitySquid['Squid'/104, l='MpServer', x=-306.44, y=55.34, z=194.47], EntityBat['Bat'/105, l='MpServer', x=-301.25, y=18.10, z=222.25], EntitySkeleton['Skeleton'/106, l='MpServer', x=-300.69, y=46.00, z=208.69], EntitySkeleton['Skeleton'/107, l='MpServer', x=-286.29, y=44.81, z=216.50], EntityCreeper['Creeper'/109, l='MpServer', x=-301.50, y=17.00, z=226.50], EntitySkeleton['Skeleton'/122, l='MpServer', x=-277.93, y=49.00, z=135.50], EntitySkeleton['Skeleton'/123, l='MpServer', x=-281.88, y=47.00, z=136.56], EntityItem['item.item.seeds'/124, l='MpServer', x=-280.06, y=65.13, z=133.91], EntityItem['item.item.seeds'/125, l='MpServer', x=-284.94, y=68.13, z=134.66], EntityZombie['Zombie'/126, l='MpServer', x=-276.88, y=44.00, z=147.63], EntityZombie['Zombie'/127, l='MpServer', x=-281.50, y=44.00, z=146.98], EntityCreeper['Creeper'/128, l='MpServer', x=-279.22, y=54.00, z=147.88], EntityCreeper['Creeper'/129, l='MpServer', x=-277.41, y=54.00, z=149.06], EntitySkeleton['Skeleton'/130, l='MpServer', x=-275.44, y=15.00, z=205.16], EntityWitch['Witch'/131, l='MpServer', x=-285.94, y=27.00, z=200.16], EntitySkeleton['Skeleton'/132, l='MpServer', x=-280.50, y=27.00, z=201.91], EntityCreeper['Creeper'/133, l='MpServer', x=-276.95, y=25.00, z=213.40], EntityItem['item.tile.flower2.blueOrchid'/134, l='MpServer', x=-283.31, y=62.13, z=202.53], EntityItem['item.tile.flower2.blueOrchid'/135, l='MpServer', x=-283.34, y=63.13, z=200.53], EntityItem['item.tile.flower2.blueOrchid'/136, l='MpServer', x=-279.94, y=64.13, z=202.97], EntityCreeper['Creeper'/137, l='MpServer', x=-278.63, y=25.00, z=212.69], EntitySkeleton['Skeleton'/138, l='MpServer', x=-275.47, y=26.00, z=221.09], EntityCreeper['Creeper'/139, l='MpServer', x=-278.38, y=25.00, z=208.66], EntitySheep['Sheep'/140, l='MpServer', x=-257.16, y=67.00, z=99.06], EntitySkeleton['Skeleton'/141, l='MpServer', x=-260.50, y=25.00, z=135.50], EntityCreeper['Creeper'/142, l='MpServer', x=-259.50, y=34.00, z=139.50], EntityZombie['Zombie'/143, l='MpServer', x=-260.50, y=33.00, z=137.50], EntitySkeleton['Skeleton'/144, l='MpServer', x=-258.50, y=33.00, z=133.50], EntityZombie['Zombie'/145, l='MpServer', x=-262.31, y=30.00, z=220.31], EntityCreeper['Creeper'/146, l='MpServer', x=-263.38, y=27.00, z=219.94], EntityCreeper['Creeper'/147, l='MpServer', x=-261.59, y=32.00, z=221.69], EntityZombie['Zombie'/148, l='MpServer', x=-259.84, y=32.00, z=222.31], EntityZombie['Zombie'/149, l='MpServer', x=-260.69, y=32.00, z=221.91], EntityEnderman['Enderman'/150, l='MpServer', x=-262.59, y=32.00, z=226.59], EntityZombie['Zombie'/151, l='MpServer', x=-261.25, y=32.00, z=225.56], EntityBat['Bat'/152, l='MpServer', x=-264.52, y=30.36, z=221.43], EntitySheep['Sheep'/156, l='MpServer', x=-244.06, y=65.00, z=90.09], EntitySkeleton['Skeleton'/157, l='MpServer', x=-255.13, y=23.00, z=143.50], EntityCreeper['Creeper'/158, l='MpServer', x=-241.50, y=20.00, z=161.72], EntityZombie['Zombie'/159, l='MpServer', x=-250.97, y=28.00, z=207.50], EntitySheep['Sheep'/161, l='MpServer', x=-225.19, y=63.00, z=77.16], EntitySheep['Sheep'/163, l='MpServer', x=-236.72, y=63.00, z=94.56], EntitySheep['Sheep'/165, l='MpServer', x=-224.94, y=63.00, z=115.91], EntityCreeper['Creeper'/166, l='MpServer', x=-228.50, y=17.00, z=174.50], EntityCreeper['Creeper'/167, l='MpServer', x=-230.50, y=33.00, z=170.50], EntityBat['Bat'/168, l='MpServer', x=-232.11, y=21.80, z=198.93], EntitySkeleton['Skeleton'/169, l='MpServer', x=-227.38, y=34.00, z=181.07], EntityZombie['Zombie'/170, l='MpServer', x=-228.33, y=20.00, z=179.39], EntityZombie['Zombie'/171, l='MpServer', x=-225.50, y=21.00, z=207.50], EntityZombie['Zombie'/172, l='MpServer', x=-232.78, y=44.00, z=202.50], EntitySheep['Sheep'/175, l='MpServer', x=-222.91, y=63.00, z=79.09], EntitySheep['Sheep'/176, l='MpServer', x=-223.09, y=63.00, z=84.91], EntityZombie['Zombie'/435, l='MpServer', x=-315.50, y=23.00, z=228.50], EntityZombie['Zombie'/436, l='MpServer', x=-317.50, y=23.00, z=228.50], EntityClientPlayerMP['Enigmas'/245, l='MpServer', x=-295.90, y=70.62, z=151.64]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 157143152 bytes (149 MB) / 330031104 bytes (314 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-211.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Technomagi{0.1.1.7-beta} [Technomagi] (Technomagi-0.1.1.7-beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore: -[1.7.10]3.0.0RC7-211
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics Family GL version 3.0.0 - Build 8.15.10.2291, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [x64 HD Kingdom Keys Resource Pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Anigmatics** [comment] 2015-04-03 06:31
Actualy, upon further tinkering, this seams to happen if I create a world with TechnoMagi, the uninstall the mod and reinstall it.

**Comment by ollieread** [comment] 2015-04-03 12:47
Duplicate of #17

**Closed by ollieread** 2015-04-03 12:47 UTC
Labels: duplicate

**Comment by ollieread** [comment] 2015-04-04 22:02
ignore that ^
